### ISSUE TITLE
Error adding the plugin

### ISSUE THREAD

**Issue by ghost** [DavidStrausz/cordova-plugin-live-ocr#3]
I'm trying to install the plugin. But i'm getting an 404 error and not able to install, when using the command 
ionic cordova plugin add cordova-plugin-live-ocr

Getting following error:
Error: Registry returned 404 for GET on https://registry.npmjs.org/cordova-plugin-live-ocr

**Comment by DavidStrausz** [comment]
This is because the plugin is not published on npm. You have to directly install it from this repository, you can also clone it and then install it from your local location.

`cordova plugin add https://github.com/DavidStrausz/cordova-plugin-live-ocr.git --save`

**Comment by ghost** [comment]
Thanks for the quick response.
